#pragma once

#ifndef STORYPROGRESS_H
#define STORYPROGRESS_H

#include <map>
#include <string>


std::map<uint16_t, std::string> eStoryProgress = {
    {0, "None"},
    {13, "Control of Reks"},
    {16, "Moved through gate in Aerial Gardens"},
    {19, "Reached lower apartments"},
    {21, "Spoke to Basch at save crystal"},
    {22, "Reks will fight 3 soldiers"},
    {23, "Reks vanquished the 3 soldiers"},
    {25, "Got control of Vaan"},
    {40, "Vaan Ratsbane! Escaped imperials"},
    {45, "Spoke to Migelo"},
    {65, "Accepted Rogue Tomato hunt"},
    {68, "Spoke to gaurd at eastgate"},
    {78, "Vanquished Rogue Tomato"},
    {85, "Returned to Rabanastre, spoke with Kytes"},
    {105, "Saw Vayne"},
    {120, "Spoke with Dalan"},
    {546, "Flew to Bhujerba"},
    {550, "Lamont joined party"},
    {580, "Entered Lhusu for the first time"},
    {610, "Saw Marquis exit the Mines with Gabranth"},
    {645, "Ambushed by Ba'Gamnan and his crew"},
    {660, "Defeated Ba'Gamnan and his crew"},
    {680, "Exited Lhusu mines, saw Lamont leave with Penelo"},
    {710, "Basch lives!"},
    {730, "Spoke with resistance"},
    {920, "Met with Ondore, took to Leviathan"},
    {930, "Vossler explains detection system Leviathan"},
    {966, "Defeated Judges gaurding Ashe's cell"},
    {970, "Ashe joins the party"},
    {990, "Left the cell-room"},
    {1000, "Penelo joins the party, Vossler leaves the party"},
    {1100, "Defeated Judge Ghis"},
    {1240, "Visited Ondore and flew to Westersand"},
    {1270, "Entered Ogir-Yensa"},
    {1330, "Vossler joined the party"},
    {1338, "Entered Nam-Yensa"},
    {1345, "Entered Tomb of Raithwall"},
    {1360, "Defeated Garuda"},
    {1364, "Teleported inside Raithwall"},
    {1372, "Defeated Demon Wall"},
    {1374, "Cutscene in Royal Passage"},
    {1376, "Cloister of Flame"},
    {1380, "Defeated Belias"},
    {1390, "Obtained Dawn Shard"},
    {1580, "Defeated Vossler"},
    {1626, "Arrived at Jahara and talking to War-chref Supinelu"},
    {1627, "Spoke about Nethicite with a Garif Elder"},
    {1678, "Spoke to War-chief Supinelu about meeting the Great-chief"},
    {1650, "Met with Great-chief and Larsa joins the party"},
    {1660, "Arrived at Sunlit Path and seeing the scene with the Judges in Archades"},
    {1700, "Passage to Eruyt opened"},
    {1740, "Entered Eruyt"},
    {1745, "Entered The Spiritwood"},
    {1756, "Spoke with Jote"},
    {1790, "Hey Fran...  how old were you again... ?"},
    {1810, "Cutscene before entering Henne Mines"},
    {1820, "Saw Mjrn run away"},
    {1950, "Defeated Tiamat"},
    {1976, "Paramina Rift cutscene"},
    {1982, "Arrived at Sand-strewn Pass"},
    {1984, "Arrived at Temple Approach"},
    {1986, "Arrived at Temple Grounds"},
    {2050, "Spoke with Gran Kiltias, Larsa leaves"},
    {2057, "Arrived at Stiltshrine of Miriam"},
    {2100, "Defeated Vinuskar"},
    {2150, "Defeated Mateus"},
    {2200, "Obtained Sword of Kings"},
    {2250, "Cutscene before leaving Stiltshrine"},
    {2290, "Returning to Temple Approach"},
    {3050, "Defeated Judge Bergan"},
    {3070, "Fixed gate to Phon Coast"},
    {3100, "Cutscene before arriving at Hunters' Camp"},
    {3130, "Cutscene before arriving at Doubt Abandoned"},
    {3150, "Defeated Topstalk"},
    {3200, "Defeated Ahriman"},
    {3210, "Cutscene before arriving at Alley of Low Whispers"},
    {3250, "Cutscene before arriving at Trant"},
    {3253, "Balthier Leaves the party"},
    {3255, "Spoke to cab guide, reencountering Jules"},
    {3260, "Reuiniting with Balthier"},
    {3300, "Cutscene in Tsenoble"},
    {3330, "Reencountered Jules in Tsenoble"},
    {3350, "Arrived at Draklor Lab 66th Floor"},
    {3355, "Saw dead soldiers"},
    {3400, "Got lab access card"},
    {3440, "Arrived at 70th floor"},
    {4150, "Defeated Cid and arriving at Balfonheim port"},
    {4160, "Mist barrier in Feywood disappeared"},
    {4200, "Defeated Rafflesia"},
    {4250, "Arrived at Gate of Earth"},
    {4295, "Arrived at Gate of Water"},
    {4300, "Defeated Daedalus"},
    {4320, "Cutscene before entering The Haalmikah Water-Steps"},
    {4350, "Defeated Tyrant"},
    {4370, "Cutscene before entering Crystal Core"},
    {4400, "Defeated Shemhazai"},
    {5100, "Met Occuria"},
    {5160, "Reddas joins the party"},
    {5200, "Arrived at Footfalls of the Past"},
    {5300, "Defeated Hydro"},
    {5303, "Arrived at The Wellspring"},
    {5320, "Arrived at Wellspring Ravel - 1st Flight"},
    {5370, "Arrived at Empyrean Ravel (97F)"},
    {6110, "Defeated Gabranth, Cid, Famfrit and arriving at Balfonheim"}
};



#endif



